name: Tomondre's portfolio webpage
run-name: CI & CD worfklows for the Kubernetes deployment 🚀
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tomondre/celebrator-3000:${{ github.run_number }}

  CD:
    runs-on: self-hosted
    needs: CI
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      KUBE_CONFIG_PATH: ~/kubeconfig.yaml
      TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Terraform Initialize
        working-directory: infrastructure
        run: terraform init
      - name: Set-up kube config
        run: echo "${{ secrets.KUBE_CONFIG }}" > ~/kubeconfig.yaml
      - name: Terraform apply
        working-directory: infrastructure
        run: |
          terraform apply -auto-approve \
          -var "image_tag=${{ github.run_number }}" \
          -var "basin_host=${{ secrets.CELEBRATOR_BASIN_HOST }}" \
          -var "database_url=${{ secrets.CELEBRATOR_DATABASE_URL }}" \
          -var "rabbitmq_username=${{ secrets.CELEBRATOR_RABBITMQ_USERNAME }}" \
          -var "rabbitmq_password=${{ secrets.CELEBRATOR_RABBITMQ_PASSWORD }}" \
          -var "rabbitmq_host=${{ secrets.CELEBRATOR_RABBITMQ_HOST }}" \
          -var "rabbitmq_port=${{ secrets.CELEBRATOR_RABBITMQ_PORT }}" \
          -var "mails=${{ secrets.CELEBRATOR_EMAILS }}"
