name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show secret
        run:  echo ${{ secrets.TERRAFORM_CLOUD_TOKENS }}
      - name: terraform plan
        uses: dflook/terraform-plan@v1
        env:
          TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TERRAFORM_CLOUD_TOKENS }}
        with:
          path: ./infrastructure
